spring:
  datasource:
    url: jdbc:mysql://mysql.goormthon-2.svc.cluster.local:3306/mydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: myuser
    password: mypassword

#  # H2 콘솔 활성화
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: true  # 외부에서 접근 허용 (개발용)

  mvc:
    servlet:
      path: /api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed-origin: "*"

logging:
  level:
    com.example.demo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
