spring:
  # H2 데이터베이스 설정
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # MySQL 설정 (주석처리)
  #  datasource:
  #    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/groomthon2
  #    username: ${MYSQL_USERNAME}
  #    password: "${MYSQL_PASSWORD}"
  #    driver-class-name: com.mysql.cj.jdbc.Driver

  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # 외부에서 접근 허용 (개발용)

  mvc:
    servlet:
      path: /api

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed-origin: "*"

logging:
  level:
    com.example.demo: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

