apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1 #FIXME: replica 수 조정
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:

      containers:
        - name: backend
          image: 837126493345.dkr.ecr.ap-northeast-2.amazonaws.com/goormthon-2/backend:build-26
          ports:
            - containerPort: 8080
         volumeMounts:
           - name: config-volume
             mountPath: /app/src/main/resources
             readOnly: true
#          command:
#            - "sleep"
#            - "3600"
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: backend-literals
                  key: SPRING_PROFILES_ACTIVE
     volumes:
       - name: config-volume
         configMap:
           name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8080
